Preprocessing phase

In [1]:
import pandas as pd

In [9]:
df=pd.read_csv("customer_churn_data.csv")

In [10]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,NaN,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,NaN,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,NaN,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,NaN,56.67,No,Yes

In [11]:
# Filling this null values to increase the model accuarcy
df.isna().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
MonthlyCharges       0
ContractType         0
InternetService    297
TotalCharges         0
TechSupport          0
Churn                0
dtype: int64

In [12]:
df['InternetService']=df['InternetService'].fillna("")

In [13]:
df.isna().sum()

CustomerID         0
Age                0
Gender             0
Tenure             0
MonthlyCharges     0
ContractType       0
InternetService    0
TotalCharges       0
TechSupport        0
Churn              0
dtype: int64

In [14]:
# Checking duplicated values

df.duplicated().sum()

np.int64(0)

In [15]:
# Counting churn majority churn is yes so model is biased that learns only the majority
# data and neglate data so we fix this

df['Churn'].value_counts()

Churn
Yes    883
No     117
Name: count, dtype: int64

Machine learning Phase

In [16]:
# Feature engineering is starts -->

In [17]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'MonthlyCharges',
       'ContractType', 'InternetService', 'TotalCharges', 'TechSupport',
       'Churn'],
      dtype='object')

In [18]:
y=df[['Churn']]

In [19]:
y

    Churn
0     Yes
1     Yes
2     Yes
3     Yes
4     Yes
..    ...
995   Yes
996   Yes
997   Yes
998   Yes
999   Yes

[1000 rows x 1 columns]

In [20]:
x=df[['Age','Gender','Tenure','MonthlyCharges']]

In [21]:
x

     Age  Gender  Tenure  MonthlyCharges
0     49    Male       4           88.35
1     43    Male       0           36.67
2     51  Female       2           63.79
3     60  Female       8          102.34
4     42    Male      32           69.01
..   ...     ...     ...             ...
995   42    Male      41           37.14
996   62    Male       9           80.93
997   51  Female      15          111.72
998   39    Male      68           65.67
999   50    Male       1           56.67

[1000 rows x 4 columns]

In [22]:
# Encode the columns in the x and y data column like Gender and churn convert into numeric value

In [23]:
# For y churn means = 1 and not churn means = 0
y['Churn']=y['Churn'].apply(lambda x : 1 if x=='Yes' else 0)

C:\Users\sande\AppData\Local\Temp\ipykernel_23776\2831345305.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Churn']=y['Churn'].apply(lambda x : 1 if x=='Yes' else 0)

In [24]:
y

     Churn
0        1
1        1
2        1
3        1
4        1
..     ...
995      1
996      1
997      1
998      1
999      1

[1000 rows x 1 columns]

In [25]:
# Now encode the x columns like Gender for female = 1 for Male = 0

x['Gender']=x['Gender'].apply(lambda x: 1 if x=='Female' else 0)

C:\Users\sande\AppData\Local\Temp\ipykernel_23776\1187319645.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Gender']=x['Gender'].apply(lambda x: 1 if x=='Female' else 0)

In [26]:
x

     Age  Gender  Tenure  MonthlyCharges
0     49       0       4           88.35
1     43       0       0           36.67
2     51       1       2           63.79
3     60       1       8          102.34
4     42       0      32           69.01
..   ...     ...     ...             ...
995   42       0      41           37.14
996   62       0       9           80.93
997   51       1      15          111.72
998   39       0      68           65.67
999   50       0       1           56.67

[1000 rows x 4 columns]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
x_train

     Age  Gender  Tenure  MonthlyCharges
474   61       0       1           79.20
437   31       0      63           75.14
638   32       1      24           57.65
486   38       0      79           30.97
543   59       0       9           91.55
..   ...     ...     ...             ...
424   51       0      45           60.90
523   50       0       8           72.96
593   48       1      36           66.29
819   55       0      41           60.69
80    42       0       7           98.48

[800 rows x 4 columns]

In [30]:
y_train

     Churn
474      1
437      0
638      1
486      0
543      1
..     ...
424      1
523      1
593      0
819      1
80       1

[800 rows x 1 columns]

In [31]:
# We use scale the data using standard scaler
from sklearn.preprocessing import StandardScaler

In [32]:
# Initialize the standard scaler
scaler=StandardScaler()

In [33]:
X_train=scaler.fit_transform(x_train)

In [34]:
# # Save the trained scaler object to a file so it can be reused later without retraining
import joblib
joblib.dump(scaler,'scaler.pkl')

['scaler.pkl']

In [35]:
# X test values are also scaled

X_test=scaler.fit_transform(x_test)

In [36]:
X_train

array([[ 1.67606811, -1.0944415 , -0.95413943,  0.21340198],
       [-1.44195643, -1.0944415 ,  2.31915671,  0.0540153 ],
       [-1.33802228,  0.91370804,  0.26014785, -0.63260366],
       ...,
       [ 0.32492414,  0.91370804,  0.89368904, -0.29341625],
       [ 1.0524632 , -1.0944415 ,  1.15766453, -0.51325994],
       [-0.29868077, -1.0944415 , -0.63736883,  0.97029241]],
      shape=(800, 4))

In [37]:
X_test

array([[ 0.0120054 ,  0.98019606,  0.07643258, -1.29625075],
       [-0.18008098, -1.02020406, -0.67448396,  0.80414593],
       [-0.27612417, -1.02020406, -0.56721017, -1.08556807],
       [ 0.87639412,  0.98019606, -0.94266843,  1.52772937],
       [ 1.0684805 ,  0.98019606, -0.88903154, -0.17702263],
       [ 0.68430773,  0.98019606,  2.86555112, -0.02383324],
       [ 0.49222135,  0.98019606, -0.88903154, -0.30562606],
       [ 0.58826454, -1.02020406, -0.08447811,  1.21908113],
       [ 0.10804859,  0.98019606,  0.23734326,  0.5147882 ],
       [ 1.54869645, -1.02020406,  0.45189084, -1.26183042],
       [-0.46821055, -1.02020406,  2.0609977 ,  1.01331563],
       [ 1.74078283, -1.02020406, -0.51357327,  0.15242911],
       [ 0.78035092,  0.98019606,  0.61280153, -0.99100672],
       [-0.66029694, -1.02020406, -0.99630533,  0.81511504],
       [-1.33259927, -1.02020406, -0.45993638,  0.85672204],
       [ 1.74078283, -1.02020406, -0.67448396,  1.5871139 ],
       [-0.56425375, -1.02020406, -0.99630533,  0.39223669],
       [-0.94842651,  0.98019606, -0.08447811, -0.90476677],
       [-3.0613767 ,  0.98019606, -0.94266843, -1.49407309],
       [ 0.68430773,  0.98019606, -0.88903154,  1.49709149],
       [ 0.58826454, -1.02020406,  0.07643258,  1.23723691],
       [-0.85238332,  0.98019606, -0.56721017, -1.34239669],
       [-1.14051289,  0.98019606, -0.83539464,  0.08623617],
       [-0.85238332,  0.98019606, -0.40629948, -0.07073567],
       [-0.46821055, -1.02020406,  1.09553358, -0.34534183],
       [ 0.87639412,  0.98019606, -0.94266843,  0.34609075],
       [-0.18008098,  0.98019606, -0.56721017, -1.53530184],
       [ 0.30013497,  0.98019606, -0.51357327,  1.19411693],
       [-1.90885842,  0.98019606, -0.72812085, -1.45965276],
       [-0.56425375,  0.98019606,  0.82734911,  0.88811641],
       [ 1.35661007, -1.02020406, -0.78175775, -0.23602891],
       [-0.37216736,  0.98019606, -0.67448396, -0.77540684],
       [ 0.39617816,  0.98019606, -0.35266259,  0.72131019],
       [ 2.12495559,  0.98019606,  1.36371806,  0.29691885],
       [-0.46821055, -1.02020406, -0.88903154, -0.09645636],
       [ 0.0120054 , -1.02020406, -0.13811501, -0.64604692],
       [ 1.26056688, -1.02020406,  0.45189084, -1.14343961],
       [ 1.35661007, -1.02020406, -0.35266259, -0.9758769 ],
       [ 1.54869645, -1.02020406, -0.83539464,  0.21105715],
       [-1.14051289, -1.02020406,  1.36371806, -1.02315758],
       [-0.37216736, -1.02020406, -0.72812085,  0.43460018],
       [ 0.30013497, -1.02020406,  0.45189084, -1.4974773 ],
       [-0.56425375,  0.98019606,  0.23734326,  1.42787259],
       [-0.37216736,  0.98019606, -0.99630533, -1.60225128],
       [ 2.12495559,  0.98019606,  0.9346229 , -0.14525001],
       [-0.08403779, -1.02020406, -0.56721017, -1.54513622],
       [ 0.39617816, -1.02020406,  4.04556282,  0.47923313],
       [-0.66029694, -1.02020406, -0.51357327,  1.0322279 ],
       [ 0.39617816,  0.98019606, -0.94266843,  0.1206565 ],
       [ 0.78035092,  0.98019606, -0.45993638,  1.04244053],
       [-1.33259927,  0.98019606,  0.61280153, -1.63137617],
       [ 1.45265326,  0.98019606, -0.2453888 ,  1.23269796],
       [-0.37216736,  0.98019606, -0.94266843,  0.3789981 ],
       [-0.94842651,  0.98019606,  0.61280153, -1.05076949],
       [ 0.20409178, -1.02020406, -0.56721017, -0.43649897],
       [ 1.74078283,  0.98019606, -0.94266843,  1.16953098],
       [-0.18008098, -1.02020406, -0.99630533,  1.03676685],
       [ 0.30013497, -1.02020406,  0.34461705, -1.53757131],
       [-0.56425375,  0.98019606, -0.94266843,  0.24509923],
       [-1.62072884,  0.98019606, -0.45993638,  1.27506145],
       [ 0.10804859, -1.02020406, -0.29902569, -1.10599332],
       [ 0.20409178,  0.98019606,  0.02279568,  0.18987541],
       [ 0.68430773,  0.98019606, -0.35266259, -0.03820657],
       [-0.66029694, -1.02020406,  0.39825395, -0.90098431],
       [-0.66029694, -1.02020406, -0.78175775,  0.62637059],
       [ 0.68430773, -1.02020406, -0.67448396, -1.27279954],
       [-1.14051289, -1.02020406,  0.29098016,  1.02541948],
       [ 0.20409178,  0.98019606, -0.67448396,  0.11952176],
       [-0.56425375,  0.98019606, -0.35266259,  1.59430056],
       [ 0.49222135,  0.98019606,  2.75827733, -0.3234036 ],
       [-0.85238332, -1.02020406,  0.50552774,  0.82116697],
       [-0.27612417,  0.98019606,  1.20280737, -0.80528823],
       [-1.14051289,  0.98019606,  1.14917048,  0.21597434],
       [-0.46821055,  0.98019606,  0.72007532,  0.6055671 ],
       [-0.27612417,  0.98019606,  1.20280737, -0.0476627 ],
       [ 0.10804859,  0.98019606,  0.55916463,  1.40290839],
       [-0.37216736,  0.98019606, -0.88903154, -1.30721987],
       [-1.42864246, -1.02020406,  0.18370637,  0.17323261],
       [ 1.26056688, -1.02020406,  0.34461705, -0.73077389],
       [-1.71677203,  0.98019606, -0.40629948, -1.41350682],
       [ 0.87639412, -1.02020406, -0.13811501,  0.15885928],
       [ 0.49222135,  0.98019606,  2.0609977 , -0.83100892],
       [ 0.20409178, -1.02020406, -0.99630533, -0.75498159],
       [-0.18008098,  0.98019606, -0.67448396, -1.2508613 ],
       [-0.18008098, -1.02020406, -0.94266843, -1.19298976],
       [-0.08403779,  0.98019606,  0.34461705,  1.51222131],
       [ 0.58826454, -1.02020406,  0.72007532,  1.23837164],
       [-0.27612417, -1.02020406,  0.55916463,  0.98003004],
       [-1.52468565,  0.98019606, -0.88903154, -0.13276792],
       [ 0.30013497,  0.98019606, -0.67448396,  0.96452198],
       [ 1.45265326,  0.98019606, -0.99630533, -0.38997479],
       [ 0.39617816, -1.02020406,  0.55916463, -1.67033545],
       [-0.75634013,  0.98019606,  0.66643842,  0.05030286],
       [-1.33259927,  0.98019606,  0.61280153, -0.18042684],
       [ 2.0289124 , -1.02020406, -0.99630533,  0.10060949],
       [ 0.97243731, -1.02020406, -0.51357327, -0.84992119],
       [-0.27612417,  0.98019606, -0.67448396, -0.46486737],
       [ 0.0120054 , -1.02020406, -0.83539464, -0.59082309],
       [ 1.83682602, -1.02020406, -0.99630533, -0.45578948],
       [-1.0444697 ,  0.98019606, -0.94266843, -1.56367025],
       [-0.46821055, -1.02020406, -0.35266259,  1.29056951],
       [-0.27612417, -1.02020406,  1.09553358,  0.21937855],
       [-0.37216736, -1.02020406,  0.02279568,  1.12830223],
       [ 1.45265326, -1.02020406,  0.02279568,  1.52583814],
       [ 0.20409178, -1.02020406,  0.34461705, -1.54778394],
       [-1.0444697 , -1.02020406, -0.2453888 ,  0.49020225],
       [ 0.20409178, -1.02020406, -0.51357327,  0.34571251],
       [-0.27612417,  0.98019606, -0.67448396, -0.26817977],
       [ 0.39617816,  0.98019606, -0.94266843, -1.58106954],
       [ 0.97243731,  0.98019606, -0.45993638, -0.12444652],
       [-1.33259927, -1.02020406, -0.67448396,  0.49738891],
       [-0.66029694,  0.98019606,  0.72007532, -1.20395888],
       [-1.42864246, -1.02020406, -0.94266843,  1.12338504],
       [ 0.30013497,  0.98019606,  0.45189084,  0.06883688],
       [ 0.10804859,  0.98019606, -0.67448396,  1.07572612],
       [ 0.78035092, -1.02020406, -0.35266259,  1.31780317],
       [ 0.10804859, -1.02020406,  1.79281322,  1.16120958],
       [-1.23655608, -1.02020406, -0.94266843, -0.76179001],
       [-0.08403779,  0.98019606, -0.83539464, -0.56434591],
       [-0.56425375, -1.02020406,  0.39825395, -0.98230707],
       [-1.23655608,  0.98019606,  0.50552774, -0.70202724],
       [-1.90885842,  0.98019606, -0.67448396, -0.66344621],
       [-0.08403779,  0.98019606, -0.35266259,  1.62872089],
       [-0.75634013,  0.98019606, -0.45993638, -0.2243033 ],
       [-1.42864246,  0.98019606, -0.56721017,  0.9622525 ],
       [ 0.58826454,  0.98019606,  0.72007532, -0.60292694],
       [ 0.78035092,  0.98019606,  2.70464044, -1.71875086],
       [ 1.83682602,  0.98019606, -0.13811501,  0.26628098],
       [-1.71677203, -1.02020406, -0.99630533,  1.4755315 ],
       [ 0.39617816,  0.98019606, -0.1917519 , -1.19601572],
       [-0.75634013, -1.02020406,  2.59736665,  1.3605449 ],
       [ 0.0120054 , -1.02020406,  0.66643842, -0.44028142],
       [-0.46821055,  0.98019606,  0.72007532, -1.63969757],
       [-0.66029694,  0.98019606,  0.29098016, -1.64121055],
       [-0.56425375,  0.98019606,  0.39825395, -0.37408848],
       [ 0.0120054 ,  0.98019606,  2.43645596,  0.18987541],
       [ 0.78035092, -1.02020406,  2.65100354,  1.55647602],
       [ 0.0120054 ,  0.98019606,  2.22190838,  1.6030002 ],
       [-1.14051289,  0.98019606,  0.13006947, -1.05719966],
       [-0.66029694,  0.98019606, -0.94266843, -1.05795615],
       [ 1.0684805 ,  0.98019606, -0.83539464, -1.63251091],
       [-1.23655608, -1.02020406,  0.880986  ,  1.6154823 ],
       [ 0.10804859,  0.98019606, -0.99630533,  1.52054271],
       [-0.37216736, -1.02020406,  0.23734326, -0.99327619],
       [-0.56425375, -1.02020406,  0.07643258,  1.17255694],
       [-0.46821055,  0.98019606,  0.39825395,  1.37983542],
       [-0.46821055,  0.98019606,  1.25644427,  0.99175564],
       [ 0.0120054 , -1.02020406, -0.94266843,  1.20016886],
       [ 0.0120054 , -1.02020406, -0.94266843,  0.19327961],
       [ 0.78035092, -1.02020406,  1.09553358,  1.50579114],
       [ 2.12495559, -1.02020406,  0.18370637, -0.82646997],
       [ 1.83682602,  0.98019606, -0.99630533, -0.01059465],
       [ 0.39617816,  0.98019606, -0.88903154, -0.66911989],
       [-0.18008098,  0.98019606, -0.56721017,  1.61699528],
       [-1.42864246, -1.02020406, -0.88903154,  0.14410771],
       [ 0.68430773, -1.02020406, -0.94266843,  0.29275815],
       [ 1.45265326,  0.98019606, -0.72812085,  0.18117576],
       [ 1.45265326, -1.02020406,  0.34461705,  0.60783657],
       [ 0.30013497, -1.02020406, -0.08447811, -1.6657965 ],
       [-0.94842651,  0.98019606, -0.40629948,  0.72509264],
       [ 0.78035092, -1.02020406, -0.67448396, -0.50685261],
       [-0.66029694, -1.02020406, -0.67448396,  0.0298776 ],
       [ 0.68430773, -1.02020406,  0.07643258, -1.73009822],
       [ 0.87639412, -1.02020406,  0.02279568,  0.39072371],
       [-1.23655608,  0.98019606,  0.880986  , -0.79847981],
       [ 1.54869645,  0.98019606, -0.62084706,  1.44905433],
       [ 0.30013497, -1.02020406, -0.40629948,  1.24934076],
       [ 0.78035092,  0.98019606, -0.88903154,  0.74211368],
       [ 0.97243731,  0.98019606,  0.98825979,  1.1105247 ],
       [ 3.75768984, -1.02020406, -0.88903154,  0.34571251],
       [ 1.0684805 , -1.02020406,  1.25644427, -0.97965936],
       [ 0.49222135, -1.02020406,  1.52462874,  0.05748952],
       [ 0.30013497,  0.98019606,  0.13006947, -0.42893406],
       [ 1.16452369, -1.02020406, -0.40629948,  1.39723471],
       [-1.23655608, -1.02020406, -0.88903154, -0.83479137],
       [-0.27612417,  0.98019606,  0.07643258, -0.92632676],
       [-0.18008098,  0.98019606, -0.45993638, -1.75581891],
       [ 0.30013497,  0.98019606, -0.78175775, -1.60300777],
       [ 0.49222135, -1.02020406,  0.66643842, -0.40586109],
       [-0.75634013, -1.02020406, -0.99630533,  0.49928014],
       [ 0.87639412, -1.02020406,  4.31374729,  1.40063892],
       [-1.52468565,  0.98019606,  0.34461705, -1.05644317],
       [-0.85238332, -1.02020406,  0.13006947, -0.31546044],
       [ 0.78035092, -1.02020406,  2.32918217,  0.35025145],
       [-1.33259927, -1.02020406, -0.88903154, -0.18685701],
       [ 0.78035092, -1.02020406,  1.20280737,  0.17512384],
       [ 0.39617816, -1.02020406, -0.83539464, -1.33104933],
       [-1.0444697 , -1.02020406, -0.99630533, -0.54694662],
       [-1.62072884, -1.02020406, -0.62084706,  1.38740033],
       [-0.46821055, -1.02020406,  1.52462874,  0.09304458],
       [ 0.39617816, -1.02020406, -0.99630533,  0.983056  ],
       [ 1.64473964,  0.98019606, -0.94266843, -0.2534282 ],
       [-0.08403779,  0.98019606,  1.14917048, -0.26893626],
       [-0.66029694, -1.02020406,  1.79281322, -0.57985397],
       [ 0.39617816,  0.98019606, -0.08447811,  1.1638573 ],
       [ 1.54869645,  0.98019606, -0.03084121, -1.5799348 ],
       [-1.33259927, -1.02020406, -0.83539464,  1.28262635],
       [-1.42864246,  0.98019606, -0.1917519 ,  0.80036347],
       [-1.33259927, -1.02020406,  0.45189084,  1.25274497],
       [-1.71677203,  0.98019606, -0.35266259, -0.46146316]])

*Now Both the training and testing data is scaled and we can use this data to train our model and make predictions*

In [41]:
# This function is used to check the performance of the model
# Importing the classification model
from sklearn.metrics import accuracy_score
# It shows the accuracy in 0 and 1-> 1 is better than 0
# This function is used to check the performance of the model by calculating the accuracy score and printing it in a formatted way
def modelperformance(predictions):
    print("Accaracy Score of the model is: {:.2f}".format(accuracy_score(y_test, predictions)))

In [42]:
# We already check the best model is support vector machine for this dataset and this working so we import basially the support vector machine algorithm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report
import joblib

In [43]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [44]:
svm = SVC(probability=True, class_weight='balanced')

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid_svm = GridSearchCV(svm, param_grid, cv=5, scoring='f1')

grid_svm.fit(X_train_res, y_train_res)

best_model = grid_svm.best_estimator_

C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sande\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [45]:
y_pred = best_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.33      0.74      0.45        23
           1       0.96      0.80      0.87       177

    accuracy                           0.80       200
   macro avg       0.64      0.77      0.66       200
weighted avg       0.89      0.80      0.83       200

In [47]:
modelperformance(y_pred)

Accaracy Score of the model is: 0.80

In [48]:
# model saved sucessfully
joblib.dump(best_model, 'best_model.pkl')

print("\nModel saved successfully ✅")

Model saved successfully ✅