Preprocessing phase

In [29]:
import pandas as pd

In [30]:
df=pd.read_csv("/content/customer_churn_data.csv")

In [31]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,NaN,2208.32,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,996,42,Male,41,37.14,Month-to-Month,Fiber Optic,1522.74,Yes,Yes
996,997,62,Male,9,80.93,Month-to-Month,NaN,728.37,No,Yes
997,998,51,Female,15,111.72,Month-to-Month,Fiber Optic,1675.80,Yes,Yes
998,999,39,Male,68,65.67,One-Year,NaN,4465.56,No,Yes
999,1000,50,Male,1,56.67,Month-to-Month,NaN,56.67,No,Yes

In [32]:
# Filling this null values to increase the model accuarcy
df.isna().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
MonthlyCharges       0
ContractType         0
InternetService    297
TotalCharges         0
TechSupport          0
Churn                0
dtype: int64

In [33]:
df['InternetService']=df['InternetService'].fillna("")

In [34]:
df.isna().sum()

CustomerID         0
Age                0
Gender             0
Tenure             0
MonthlyCharges     0
ContractType       0
InternetService    0
TotalCharges       0
TechSupport        0
Churn              0
dtype: int64

In [35]:
# Checking duplicated values

df.duplicated().sum()

np.int64(0)

In [36]:
# Counting churn majority churn is yes so model is biased that learns only the majority
# data and neglate data so we fix this

df['Churn'].value_counts()

Churn
Yes    883
No     117
Name: count, dtype: int64

Machine learning Phase

In [37]:
# Feature engineering is starts -->

In [38]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'MonthlyCharges',
       'ContractType', 'InternetService', 'TotalCharges', 'TechSupport',
       'Churn'],
      dtype='object')

In [39]:
y=df[['Churn']]

In [40]:
y

    Churn
0     Yes
1     Yes
2     Yes
3     Yes
4     Yes
..    ...
995   Yes
996   Yes
997   Yes
998   Yes
999   Yes

[1000 rows x 1 columns]

In [41]:
x=df[['Age','Gender','Tenure','MonthlyCharges']]

In [42]:
x

     Age  Gender  Tenure  MonthlyCharges
0     49    Male       4           88.35
1     43    Male       0           36.67
2     51  Female       2           63.79
3     60  Female       8          102.34
4     42    Male      32           69.01
..   ...     ...     ...             ...
995   42    Male      41           37.14
996   62    Male       9           80.93
997   51  Female      15          111.72
998   39    Male      68           65.67
999   50    Male       1           56.67

[1000 rows x 4 columns]

In [43]:
# Encode the columns in the x and y data column like Gender and churn convert into numeric value

In [44]:
# For y churn means = 1 and not churn means = 0
y['Churn']=y['Churn'].apply(lambda x : 1 if x=='Yes' else 0)

/tmp/ipykernel_363/1376298929.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Churn']=y['Churn'].apply(lambda x : 1 if x=='Yes' else 0)

In [45]:
y

     Churn
0        1
1        1
2        1
3        1
4        1
..     ...
995      1
996      1
997      1
998      1
999      1

[1000 rows x 1 columns]

In [46]:
# Now encode the x columns like Gender for female = 1 for Male = 0

x['Gender']=x['Gender'].apply(lambda x: 1 if x=='Female' else 0)

/tmp/ipykernel_363/1187319645.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Gender']=x['Gender'].apply(lambda x: 1 if x=='Female' else 0)

In [47]:
x

     Age  Gender  Tenure  MonthlyCharges
0     49       0       4           88.35
1     43       0       0           36.67
2     51       1       2           63.79
3     60       1       8          102.34
4     42       0      32           69.01
..   ...     ...     ...             ...
995   42       0      41           37.14
996   62       0       9           80.93
997   51       1      15          111.72
998   39       0      68           65.67
999   50       0       1           56.67

[1000 rows x 4 columns]

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [50]:
x_train

     Age  Gender  Tenure  MonthlyCharges
807   40       1      11           45.72
630   28       1      32           84.32
508   45       0      14           53.37
675   37       1       3           78.98
11    40       1      19           36.18
..   ...     ...     ...             ...
78    45       0      22          103.34
996   62       0       9           80.93
687   41       1      33           50.35
765   37       1       1           48.93
43    41       0      10           88.87

[800 rows x 4 columns]

In [51]:
y_train

     Churn
807      1
630      1
508      0
675      1
11       0
..     ...
78       1
996      1
687      1
765      1
43       1

[800 rows x 1 columns]

In [55]:
# We use scale the data using standard scaler
from sklearn.preprocessing import StandardScaler

In [56]:
# Initialize the standard scaler
scaler=StandardScaler()

In [59]:
X_train=scaler.fit_transform(x_train)

In [60]:
# # Save the trained scaler object to a file so it can be reused later without retraining
import joblib
joblib.dump(scaler,'scaler.pkl')

['scaler.pkl']

In [61]:
# X test values are also scaled

X_test=scaler.fit_transform(x_test)

In [62]:
X_train

array([[-0.47200595,  0.93933644, -0.44065994, -1.09236466],
       [-1.69567788,  0.93933644,  0.65027536,  0.41242759],
       [ 0.03785735, -1.06458129, -0.28481204, -0.7941351 ],
       ...,
       [-0.37003329,  0.93933644,  0.70222466, -0.91186755],
       [-0.77792394,  0.93933644, -0.96015294, -0.9672252 ],
       [-0.37003329, -1.06458129, -0.49260924,  0.58980595]])

In [63]:
X_test

array([[ 0.01489363,  0.87744601,  1.57447608, -0.62986862],
       [-1.73125603,  0.87744601,  0.46917235, -1.08933166],
       [-0.60139448, -1.13967126, -0.57795751, -0.85182581],
       [-0.4986798 ,  0.87744601,  1.69082384,  0.6085825 ],
       [ 0.220323  ,  0.87744601, -0.46160974, -1.75364835],
       [-0.60139448, -1.13967126, -0.92700079,  0.52811816],
       [-0.19053574, -1.13967126, -0.86882691,  0.262236  ],
       [-0.70410917,  0.87744601,  0.76004175,  0.7232539 ],
       [-0.60139448,  0.87744601, -0.17074034, -0.45494615],
       [ 1.35018454, -1.13967126, -0.57795751,  0.99107965],
       [-0.80682386, -1.13967126,  2.03986713, -0.59954873],
       [-1.42311197,  0.87744601,  0.64369399, -0.72510419],
       [-0.08782106, -1.13967126, -0.92700079,  0.19498803],
       [ 0.01489363,  0.87744601,  0.23647683,  1.001575  ],
       [ 1.24746986,  0.87744601, -0.69430527, -0.79157473],
       [ 1.76104328, -1.13967126,  0.12012906, -0.94161935],
       [ 1.04204049,  0.87744601,  1.05091116,  0.5992533 ],
       [ 0.73389643, -1.13967126,  1.28360668,  1.54383467],
       [ 0.52846706,  0.87744601, -0.81065303,  1.20331892],
       [-0.60139448, -1.13967126,  0.41099847, -0.42656984],
       [ 0.52846706,  0.87744601, -0.51978362, -1.26036697],
       [-1.2176826 ,  0.87744601,  0.06195518,  0.85502883],
       [-1.32039728,  0.87744601, -0.92700079, -1.5371332 ],
       [ 0.9393258 , -1.13967126,  0.29465071,  1.13607095],
       [-0.4986798 , -1.13967126, -0.34526198, -1.7291592 ],
       [-1.62854134,  0.87744601, -0.51978362,  0.9852489 ],
       [ 0.11760831,  0.87744601, -0.57795751,  0.61208095],
       [ 0.52846706,  0.87744601,  0.87638951, -0.62326044],
       [ 0.52846706,  0.87744601, -0.51978362,  0.19693161],
       [ 0.220323  , -1.13967126,  2.67977982,  0.82976225],
       [ 0.83661111, -1.13967126, -0.75247915,  0.36097002],
       [ 0.32303769, -1.13967126, -0.57795751,  0.21520129],
       [ 1.86375797,  0.87744601, -0.98517467, -0.01453023],
       [-1.01225323, -1.13967126, -0.75247915,  1.44237964],
       [ 0.52846706, -1.13967126, -0.75247915,  0.16039225],
       [ 0.11760831, -1.13967126,  0.70186787,  1.48669333],
       [-0.4986798 ,  0.87744601, -0.63613139, -0.80051522],
       [ 1.35018454, -1.13967126, -0.40343586, -0.87514881],
       [ 0.32303769,  0.87744601, -0.81065303,  0.86202573],
       [ 1.86375797,  0.87744601, -0.40343586,  0.53705865],
       [-0.08782106, -1.13967126,  1.57447608,  0.7279185 ],
       [-1.32039728,  0.87744601, -0.75247915, -1.62770417],
       [-1.32039728, -1.13967126,  3.55238803,  0.9502644 ],
       [ 1.35018454,  0.87744601, -0.98517467,  1.12829661],
       [-0.29325043, -1.13967126, -0.57795751,  0.83520429],
       [-0.60139448, -1.13967126, -0.92700079,  1.31449187],
       [ 0.73389643,  0.87744601, -0.22891422,  0.25562782],
       [ 0.52846706,  0.87744601, -0.98517467,  1.05444046],
       [ 0.32303769,  0.87744601,  0.0037813 ,  1.45870573],
       [-0.4986798 ,  0.87744601, -0.75247915,  1.52517627],
       [-0.60139448, -1.13967126,  2.97064922, -0.44017492],
       [ 0.220323  , -1.13967126, -0.34526198, -1.52586042],
       [ 0.63118174, -1.13967126, -0.2870881 , -1.1767929 ],
       [-1.01225323,  0.87744601, -0.34526198, -0.07633617],
       [ 0.73389643,  0.87744601, -0.92700079,  1.36152658],
       [-0.90953854, -1.13967126,  0.06195518,  1.34947637],
       [ 0.42575237,  0.87744601,  0.41099847, -1.49865025],
       [ 0.63118174,  0.87744601,  0.52734623, -0.6947843 ],
       [-1.11496791, -1.13967126, -0.34526198, -0.44172978],
       [-0.60139448, -1.13967126, -0.81065303, -0.27302677],
       [ 0.42575237, -1.13967126, -0.63613139,  1.05327431],
       [-1.01225323, -1.13967126,  0.23647683, -0.32783582],
       [-0.80682386, -1.13967126, -0.92700079,  0.19809776],
       [ 0.42575237,  0.87744601, -0.40343586, -0.47166096],
       [ 0.01489363,  0.87744601, -0.2870881 ,  1.56016077],
       [-1.42311197, -1.13967126, -0.86882691, -0.86154372],
       [-0.29325043,  0.87744601, -0.17074034, -1.18689953],
       [-1.83397071, -1.13967126, -0.57795751,  1.42216637],
       [-1.52582665,  0.87744601,  1.16725892, -0.68351152],
       [ 0.32303769,  0.87744601, -0.22891422, -1.23821012],
       [ 1.55561391,  0.87744601, -0.57795751,  1.48552718],
       [-3.37469099,  0.87744601, -0.92700079, -1.53907678],
       [ 0.32303769, -1.13967126, -0.75247915,  0.29644306],
       [ 0.52846706,  0.87744601, -0.63613139,  1.12985148],
       [-0.70410917, -1.13967126, -0.75247915,  0.98252788],
       [ 0.220323  ,  0.87744601,  0.0037813 ,  1.14501143],
       [ 0.11760831, -1.13967126, -0.51978362, -1.14997145],
       [ 0.42575237,  0.87744601,  0.0037813 ,  0.78700343],
       [-0.60139448, -1.13967126,  1.2254328 , -0.31423073],
       [-1.32039728, -1.13967126, -0.98517467, -1.0527923 ],
       [-1.9366854 , -1.13967126, -0.34526198,  1.59242425],
       [ 2.17190203,  0.87744601, -0.98517467,  0.35552799],
       [ 1.04204049,  0.87744601, -0.86882691, -0.18556554],
       [ 1.55561391,  0.87744601, -0.05439258, -0.88370057],
       [-0.90953854,  0.87744601,  0.41099847,  0.66455769],
       [ 0.32303769, -1.13967126,  2.27256265, -1.73693354],
       [-1.42311197,  0.87744601, -0.51978362,  0.14717588],
       [ 0.52846706,  0.87744601, -0.81065303, -1.53441218],
       [-1.01225323,  0.87744601,  0.93456339,  0.91372504],
       [ 0.52846706, -1.13967126, -0.57795751,  0.55999293],
       [ 0.63118174,  0.87744601, -0.86882691,  1.53489419],
       [ 0.220323  ,  0.87744601, -0.69430527, -1.75986782],
       [ 0.52846706, -1.13967126, -0.75247915,  1.31254829],
       [ 1.55561391,  0.87744601,  2.09804101,  0.48885779],
       [ 0.220323  , -1.13967126,  0.46917235, -1.58377919],
       [ 1.55561391, -1.13967126,  3.43604027,  0.21364642],
       [-1.52582665, -1.13967126, -0.63613139,  0.50751618],
       [-0.80682386,  0.87744601, -0.34526198,  1.58542735],
       [-0.80682386,  0.87744601,  2.91247534,  0.53394891],
       [-0.29325043,  0.87744601,  2.50525818, -0.40013711],
       [-0.19053574, -1.13967126,  2.85430146, -0.61937328],
       [-1.52582665, -1.13967126, -0.86882691, -0.19567217],
       [-0.4986798 ,  0.87744601, -0.17074034,  0.31238044],
       [-0.08782106, -1.13967126, -0.51978362, -1.15891193],
       [ 0.220323  ,  0.87744601,  1.2254328 ,  0.73219439],
       [ 0.73389643, -1.13967126,  1.10908504, -0.51597466],
       [-0.4986798 ,  0.87744601, -0.75247915,  0.31704504],
       [-0.60139448, -1.13967126,  0.06195518,  0.11996572],
       [ 0.9393258 , -1.13967126, -0.51978362,  0.54327811],
       [ 0.42575237,  0.87744601, -0.22891422, -0.64386242],
       [ 0.01489363, -1.13967126,  2.03986713,  1.45481857],
       [-0.08782106,  0.87744601, -0.63613139,  0.59536614],
       [-1.9366854 , -1.13967126, -0.69430527, -0.55834477],
       [-1.83397071,  0.87744601, -0.40343586,  1.30671754],
       [-2.14211477, -1.13967126, -0.05439258, -1.68601166],
       [-0.90953854, -1.13967126,  0.99273728, -0.5381315 ],
       [ 0.9393258 , -1.13967126, -0.46160974, -0.87709239],
       [-0.19053574,  0.87744601,  0.35282459,  1.21148197],
       [ 1.35018454,  0.87744601,  1.10908504,  0.17166503],
       [ 0.42575237,  0.87744601,  1.16725892, -0.61704098],
       [ 1.6583286 ,  0.87744601, -0.63613139, -1.28019152],
       [ 1.55561391, -1.13967126, -0.81065303,  0.21325771],
       [-1.11496791, -1.13967126,  0.46917235, -0.64619472],
       [ 1.35018454, -1.13967126, -0.57795751,  0.80916027],
       [ 0.220323  ,  0.87744601, -0.46160974,  1.22353218],
       [ 0.01489363, -1.13967126, -0.17074034, -0.38108999],
       [ 3.0963342 ,  0.87744601, -0.11256646,  0.477585  ],
       [-0.29325043,  0.87744601, -0.92700079, -0.238431  ],
       [ 0.01489363,  0.87744601, -0.98517467,  1.55899462],
       [-1.01225323,  0.87744601, -0.11256646,  0.39012377],
       [-0.90953854, -1.13967126,  2.91247534,  1.39456749],
       [-1.32039728,  0.87744601, -0.81065303,  0.08498123],
       [-0.60139448,  0.87744601,  1.86534549, -0.87631496],
       [ 0.11760831, -1.13967126, -0.63613139, -1.53091373],
       [ 0.220323  ,  0.87744601, -0.81065303, -0.68856483],
       [-0.80682386, -1.13967126, -0.75247915,  0.64006855],
       [ 1.86375797,  0.87744601, -0.40343586, -1.75986782],
       [ 1.14475517,  0.87744601, -0.2870881 ,  0.90128611],
       [-0.70410917, -1.13967126,  0.12012906, -0.6784582 ],
       [ 0.01489363,  0.87744601,  0.70186787,  1.43810375],
       [ 0.42575237,  0.87744601, -0.51978362, -0.52141669],
       [ 1.04204049,  0.87744601, -0.81065303, -1.68134706],
       [-0.08782106,  0.87744601, -0.2870881 , -1.35288152],
       [-1.62854134,  0.87744601,  1.10908504,  0.2785621 ],
       [ 0.52846706,  0.87744601, -0.34526198,  1.18116207],
       [ 0.42575237, -1.13967126, -0.75247915,  0.44143436],
       [-0.4986798 ,  0.87744601, -0.81065303,  0.73219439],
       [-0.39596511,  0.87744601, -0.63613139, -0.27924624],
       [ 0.11760831,  0.87744601, -0.57795751,  1.11235923],
       [ 0.01489363, -1.13967126,  0.35282459,  1.09447827],
       [ 0.52846706, -1.13967126,  0.87638951,  1.26901203],
       [-2.75840288,  0.87744601,  0.23647683, -1.06173278],
       [-0.90953854, -1.13967126, -0.98517467,  0.50945977],
       [-0.08782106, -1.13967126, -0.81065303, -0.61082151],
       [-0.29325043, -1.13967126,  0.81821563, -0.75464666],
       [-0.08782106, -1.13967126, -0.92700079, -1.82439477],
       [-1.73125603,  0.87744601, -0.86882691, -0.14008569],
       [ 0.63118174,  0.87744601, -0.69430527,  1.03306104],
       [ 0.63118174,  0.87744601,  1.34178056,  0.18604754],
       [ 0.63118174,  0.87744601,  1.57447608, -1.60826834],
       [ 0.63118174,  0.87744601,  0.41099847, -0.69206328],
       [-0.19053574,  0.87744601, -0.63613139,  0.7582384 ],
       [ 0.11760831,  0.87744601, -0.63613139,  0.11918829],
       [-1.42311197,  0.87744601,  1.05091116, -0.82422693],
       [ 1.6583286 , -1.13967126,  0.64369399,  0.53744736],
       [-0.08782106,  0.87744601,  0.41099847, -1.06173278],
       [ 0.63118174,  0.87744601,  0.35282459,  1.6639481 ],
       [-0.80682386, -1.13967126,  0.52734623, -0.94395165],
       [-0.70410917, -1.13967126,  1.63264996, -1.46483191],
       [ 0.73389643, -1.13967126, -0.46160974, -0.73248981],
       [-1.01225323,  0.87744601, -0.51978362, -1.38320142],
       [ 0.73389643,  0.87744601, -0.63613139, -0.70333606],
       [ 0.52846706, -1.13967126, -0.81065303,  0.8472545 ],
       [ 0.9393258 ,  0.87744601,  1.16725892,  1.13762581],
       [ 1.04204049,  0.87744601,  0.17830294, -1.07494915],
       [ 0.63118174,  0.87744601, -0.11256646,  1.34986508],
       [ 0.83661111,  0.87744601, -0.92700079, -1.51225533],
       [ 2.17190203, -1.13967126,  0.29465071, -0.85299196],
       [-0.60139448,  0.87744601,  0.87638951, -1.68873268],
       [ 0.32303769, -1.13967126, -0.51978362,  1.06338094],
       [ 0.32303769,  0.87744601, -0.92700079,  0.12035444],
       [ 0.01489363, -1.13967126, -0.92700079,  0.25562782],
       [ 1.86375797, -1.13967126,  0.70186787, -0.50081471],
       [-0.39596511,  0.87744601,  1.39995444, -0.83122383],
       [-0.29325043,  0.87744601, -0.63613139,  1.33042925],
       [ 1.76104328, -1.13967126, -0.63613139,  1.62740874],
       [ 0.01489363,  0.87744601, -0.17074034,  0.47875115],
       [ 0.73389643, -1.13967126,  2.62160594,  0.35630542],
       [-0.29325043,  0.87744601, -0.11256646,  0.25873755],
       [ 2.06918734,  0.87744601, -0.57795751, -1.21410969],
       [ 0.32303769, -1.13967126, -0.81065303, -1.37153992],
       [-1.11496791,  0.87744601, -0.92700079,  0.52112126],
       [ 0.01489363, -1.13967126,  0.76004175,  1.57065612],
       [-1.01225323, -1.13967126, -0.81065303,  0.15533893],
       [ 0.73389643, -1.13967126, -0.63613139, -0.52452642],
       [ 0.220323  ,  0.87744601,  0.64369399, -0.3181179 ],
       [ 0.73389643,  0.87744601, -0.11256646, -1.31439858],
       [-0.60139448, -1.13967126, -0.92700079, -0.49809369],
       [-0.39596511,  0.87744601, -0.98517467, -1.52897015],
       [-0.19053574,  0.87744601, -0.86882691, -1.52236197]])

*Now Both the training and testing data is scaled and we can use this data to train our model and make predictions*

In [64]:
# This function is used to check the performance of the model
# Importing the classification model
from sklearn.metrics import accuracy_score
# It shows the accuracy in 0 and 1-> 1 is better than 0
# This function is used to check the performance of the model by calculating the accuracy score and printing it in a formatted way
def modelperformance(predictions):
    print("Accaracy Score of the model is: {:.2f}".format(accuracy_score(y_test, predictions)))

In [66]:
# We already check the best model is support vector machine for this dataset and this working so we import basially the support vector machine algorithm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.metrics import classification_report
import joblib

In [67]:
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [72]:
svm = SVC(probability=True, class_weight='balanced')

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

grid_svm = GridSearchCV(svm, param_grid, cv=5, scoring='f1')

grid_svm.fit(X_train_res, y_train_res)

best_model = grid_svm.best_estimator_

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [73]:
y_pred = best_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.18      0.67      0.28        15
           1       0.97      0.75      0.84       185

    accuracy                           0.74       200
   macro avg       0.57      0.71      0.56       200
weighted avg       0.91      0.74      0.80       200

In [74]:
modelperformance(y_pred)

Accaracy Score of the model is: 0.74

In [75]:
# model saved sucessfully
joblib.dump(best_model, 'best_model.pkl')

print("\nModel saved successfully ✅")

Model saved successfully ✅